%YAML:1.0

# Topic name in rosbag
PointCloudTopic: "/livox/lidar"
ImageTopic: "/camera/color/image_raw"

ExtrinsicMat: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  # data: [0.0,   -1.0,   0.0,    0.0,
  #        0.0,   0.0,   -1.0,    0.0,
  #        1.0,   0.0,    0.0,    0.0,
  #        0.0,   0.0,    0.0,    1.0]

  data: [0.0314118,-0.99948,0.00722162,   -0.0846093,
         0.00650134,-0.00702072,-0.999954,-0.051063,
         0.999485,0.0314573,0.00627743,   -0.000471171,
         0.0,   0.0,    0.0,    1.0]
          
# Params for Canny Edge Extraction

Canny.gray_threshold: 10
Canny.len_threshold: 200

# Params for Voxel Cutting & Plane Fitting & Edge Extraction
Voxel.size: 0.5
Voxel.down_sample_size: 0.02
Plane.min_points_size: 30
Plane.normal_theta_min: 45
Plane.normal_theta_max: 135
Plane.max_size: 8
Ransac.dis_threshold: 0.02
Edge.min_dis_threshold: 0.03
Edge.max_dis_threshold: 0.06